services:
  app:
    container_name: ngtpa-api-server
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8888:8888"
    environment:
      SERVER_PORT: ${SERVER_PORT:-8888}
      APIM_BASEURL: ${APIM_BASEURL:?Set APIM_BASEURL in .env}
      APIM_TIMEOUTMILLISECONDS: ${APIM_TIMEOUTMILLISECONDS:?Set APIM_TIMEOUTMILLISECONDS in .env}
      APIM_CLIENT_ID: ${APIM_CLIENT_ID:?Set APIM_CLIENT_ID in .env}
      APIM_CLIENT_SECRET: ${APIM_CLIENT_SECRET:?Set APIM_CLIENT_SECRET in .env}
      APIM_TOKEN_URI: ${APIM_TOKEN_URI:?Set APIM_TOKEN_URI in .env}
