services:
  app:
    container_name: ngtpa-api-server
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "${SERVER_PORT:-8888}:${SERVER_PORT:-8888}"
    environment:
      SERVER_PORT: ${SERVER_PORT:-8888}
      SPRING_CLOUD_CONFIG_ENABLED: ${SPRING_CLOUD_CONFIG_ENABLED:-false}
      APIM_BASEURL: ${APIM_BASEURL:?Set APIM_BASEURL in .env}
      APIM_TIMEOUTMILLISECONDS: ${APIM_TIMEOUTMILLISECONDS:?Set APIM_TIMEOUTMILLISECONDS in .env}
      APIM_CERTIFICATE: ${APIM_CERTIFICATE:-}
      APIM_X_TEST_SESSION_ID: ${APIM_X_TEST_SESSION_ID:-}
      APIM_ENCRYPTION_ENABLED: ${APIM_ENCRYPTION_ENABLED:-true}
      APIM_AES_KEY: ${APIM_AES_KEY:-}
      APIM_PUBLIC_KEY_PEM: ${APIM_PUBLIC_KEY_PEM:-}
      APIM_PRIVATE_KEY_PEM: ${APIM_PRIVATE_KEY_PEM:-}
      APIM_CLIENT_ID: ${APIM_CLIENT_ID:?Set APIM_CLIENT_ID in .env}
      APIM_CLIENT_SECRET: ${APIM_CLIENT_SECRET:?Set APIM_CLIENT_SECRET in .env}
      APIM_CLIENT_AUTH_METHOD: ${APIM_CLIENT_AUTH_METHOD:-client_secret_basic}
      APIM_CLIENT_SCOPE: ${APIM_CLIENT_SCOPE:-}
      APIM_TOKEN_URI: ${APIM_TOKEN_URI:?Set APIM_TOKEN_URI in .env}
