contribution-summary:
  total-label:
    en: Total Contributions
    zh: "供款總額"
  headers:
    dealing-date: Dealing date處理日期
    contribution-period: Contribution Periods供款期
    total-contribution: Total Contributions供款總額

currency-mapping:
  zh_HK:
    AUD: 澳元
    EUR: 歐羅
    EUR.TB.HKBU: 歐元
    GBP: 英鎊
    HKD: 港元
    USD: 美元
    JPY: 日元
    SGD: 新加坡元
    CNY: 人民幣
    RMB: 人民幣
    CAD: 加幣
    AED: AED
    TWN: 新台幣
    TWD: 新台幣
    NZD: NZD
    INR: INR
    AUD.OG: 澳幣
    EUR.OG: 歐元
    GBP.OG: 英鎊
    HKD.OG: 港幣
    USD.OG: 美金
    JPY.OG: 日圓
    SGD.OG: 新加坡幣
    CNY.OG: 人民幣
    RMB.OG: 人民幣
    CAD.OG: 加拿大幣
    AED.OG: 迪拉姆
    TWD.OG: 台幣
    NZD.OG: 紐西蘭幣
    INR.OG: 印度盧比
  en:
    AUD: AUD
    EUR: EUR
    EUR.TB.HKBU: EUR
    GBP: GBP
    HKD: HKD
    USD: USD
    JPY: JPY
    SGD: SGD
    CNY: CNY
    RMB: RMB
    CAD: CAD
    AED: AED
    TWN: TWD
    TWD: TWD
    NZD: NZD
    INR: INR
    AUD.OG: AUD
    EUR.OG: EUR
    GBP.OG: GBP
    HKD.OG: HKD
    USD.OG: USD
    JPY.OG: JPY
    SGD.OG: SGD
    CNY.OG: CNY
    RMB.OG: RMB
    CAD.OG: CAD
    AED.OG: AED
    TWD.OG: TWD
    NZD.OG: NZD
    INR.OG: INR

reference-date:
  deployment-env: dev
  override-date: 04/05/2023
  override-zone-id: Asia/Hong_Kong