server:
  port: ${SERVER_PORT:8888}

spring:
  application:
    name: ngtpa-api-server
  cloud:
    config:
      enabled: ${SPRING_CLOUD_CONFIG_ENABLED:false}
  security:
    oauth2:
      client:
        registration:
          apim-client:
            client-id: ${APIM_CLIENT_ID:tpa-service-client-id}
            client-secret: ${APIM_CLIENT_SECRET:your-secure-client-secret}
            authorization-grant-type: client_credentials
            client-authentication-method: ${APIM_CLIENT_AUTH_METHOD:client_secret_basic}
            scope: ${APIM_CLIENT_SCOPE:}
        provider:
          apim-client:
            token-uri: ${APIM_TOKEN_URI:}

apim:
  baseUrl: ${APIM_BASEURL:}
  timeoutMilliseconds: ${APIM_TIMEOUTMILLISECONDS:10000}
  headers:
    certificate: ${APIM_CERTIFICATE:}
    xTestSessionId: ${APIM_X_TEST_SESSION_ID:}
  encryption:
    enabled: ${APIM_ENCRYPTION_ENABLED:true}
    aesKey: ${APIM_AES_KEY:}
    publicKeyPem: ${APIM_PUBLIC_KEY_PEM:}
    privateKeyPem: ${APIM_PRIVATE_KEY_PEM:}
    apis:
      account-balance:
        requestFields:
          - policy-no
        responseFields:
          - ECoName
          - Idno
          - EngName
          - ChinName
          - MPhone
          - Email
