spring:
  application:
    name: ngtpa-api-server
  cloud:
    config:
      enabled: ${SPRING_CLOUD_CONFIG_ENABLED:false}
  security:
    oauth2:
      client:
        registration:
          apim-client:
            client-id: ${APIM_CLIENT_ID:tpa-service-client-id}
            client-secret: ${APIM_CLIENT_SECRET:your-secure-client-secret}
            authorization-grant-type: client_credentials
        provider:
          apim-client:
            token-uri: ${APIM_TOKEN_URI:}

apim:
  baseUrl: ${APIM_BASEURL:}
  timeoutMilliseconds: ${APIM_TIMEOUTMILLISECONDS:10000}
